### ISSUE TITLE
Provide a way to select adapter

### ISSUE THREAD

**Issue by olivia-fl** [gfx-rs/gfx-render#5]
Currently the adapter is hardcoded to the first available one. In my case this doesn't work, since the integrated GPU shows up before the discrete. It would be helpful to provide some way of selecting a different adapter.

**Comment by zakarumych** [comment]
I guess it is possible to add `FnOnce` argument to the `init` function that will receive adapters to choose from.
Would this work for your case?

**Comment by olivia-fl** [comment]
Not sure if I should open a new issue for this, but it looks like the members for `AdapterByName` and `AdapterByNameRe` are private. Is there currently a way to instantiate those structs that I'm missing?

**Comment by zakarumych** [comment]
Should be OK now 😄
