### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by siriux** [gfx-rs/gfx-render#6]
Hi,

What's the status of gfx-render? Are there any examples? Should I try to use it now for a new project, or it's better to start with gfx-hal directly?

Thanks

**Comment by zakarumych** [comment]
Hi, @siriux

This project is currently undermaintained.Focus shifted toward higher-level crate [rendy](https://github.com/rustgd/rendy).
gfx-render was aimed to be middle-level helper to work with gfx-hal. But it seems that making it flexible enough means to make it do nothing on its own.
Also it is not safe to use even though functions are not marked unsafe, same as gfx-hal.
If you want to work on low-level then you'd better use gfx-hal directly, borrowing whatever you like from gfx-render and other gfx-* helper crates.

You can find examples in [xfg](https://github.com/omni-viral/xfg-rs).

**Comment by siriux** [comment]
Thanks for you answer.

Do you have an idea when rendy will be ready to use (even if not stable)? It seems even better than gfx-render.

**Comment by zakarumych** [comment]
@siriux we try to make it ASAP. The deadline is amethyst 0.10. And 0.9 was just released :)

**Comment by kvark** [comment]
I consider the question answered. Rendy is the official successor.
